### ISSUE TITLE
Notebook Error - Target -1 is out of bounds.

### ISSUE THREAD

**Issue by impulsecorp** [jonathanbgn/slogan-generator#1]
When I run your notebook on my CPU Ubuntu 18.04 server I get this error:
"IndexError: Target -1 is out of bounds."
The transformers model loads fine, and the slogans.csv file loads and shows "torch.Size([3, 64])" just like your notebook at https://github.com/jonathanbgn/slogan-generator/blob/master/GPT2_finetuning.ipynb does.  But when it starts training it gives an error.

Any idea what might be causing that?

Also, I am running it in a virtual environment, but I don't have Jupyter installed in the virtual environment, I have it installed globally. Is that a problem?  I tried using a .py file version instead but when I run that in the virtual environment I get this error:
"ModuleNotFoundError: No module named 'transformers'"
even though transformers is installed.

Here's the full error for the notebook:

from transformers import AdamW

# Move the model to the GPU:
device = torch.device('cpu')
model.to(device)

# Fine-tune GPT2 for two epochs:
optimizer = AdamW(model.parameters())
# fit(model, optimizer, train_loader, val_loader, epochs=2)
fit(model, optimizer, train_loader, val_loader, epochs=2, device=device)

Training:   0%|          | 0/2856 [00:00<?, ?it/s]
--- Starting epoch #0 ---
Training:   0%|          | 0/2856 [00:00<?, ?it/s]

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-97dfbac78667> in <module>
      8 optimizer = AdamW(model.parameters())
      9 # fit(model, optimizer, train_loader, val_loader, epochs=2)
---> 10 fit(model, optimizer, train_loader, val_loader, epochs=2, device=device)

<ipython-input-5-0e7d22eaeb2d> in fit(model, optimizer, train_dl, val_dl, epochs, device)
     20 
     21       # Call the model with the token ids, segment ids, and the ground truth (labels)
---> 22       outputs = model(inputs[:,0,:], token_type_ids=inputs[:,1,:], labels=inputs[:,2,:])
     23 
     24       # Add the loss and batch size to the list:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/transformers/modeling_gpt2.py in forward(self, input_ids, past, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels)
    607             # Flatten the tokens
    608             loss_fct = CrossEntropyLoss()
--> 609             loss = loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
    610             outputs = (loss,) + outputs
    611 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py in forward(self, input, target)
    914     def forward(self, input, target):
    915         return F.cross_entropy(input, target, weight=self.weight,
--> 916                                ignore_index=self.ignore_index, reduction=self.reduction)
    917 
    918 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
   2019     if size_average is not None or reduce is not None:
   2020         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 2021     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
   2022 
   2023 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   1836                          .format(input.size(0), target.size(0)))
   1837     if dim == 2:
-> 1838         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   1839     elif dim == 4:
   1840         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

IndexError: Target -1 is out of bounds.

**Comment by jonathanbgn** [comment]
Thanks for the report. This bug was due to the latest version of HuggingFace's Transformers library ([v2.4.0](https://github.com/huggingface/transformers/releases/tag/v2.4.0)) where they replaced the ignore tokens with -100 instead of -1 previously.

I've just updated the notebook to reflect this change. You could also use the previous version of Transformers (v2.3.0) with the old notebook to bypass this issue.

**Comment by impulsecorp** [comment]
Yes, I tried it and your new version of the notebook fixed the error, thanks.

**Comment by impulsecorp** [comment]
By the way, using a batch size of 64 (that is what you used) for validation caused my kernal to crash (due to running out of RAM), but it worked fine when I changed it to be 32 like with the training set.
