### ISSUE TITLE
segments multiplier meaning

### ISSUE THREAD

**Issue by impulsecorp** [jonathanbgn/slogan-generator#2]
What is the purpose of the "64" in this line:
segments = [slogan_tkn] * 64
If I change that, what effect would it have?

**Comment by jonathanbgn** [comment]
64 is just an arbitrary value that I set for the maximum sequence length when generating slogans. This means that the total length (context length + slogan length) should not exceed 64.

If you want to generate longer slogans (or use larger contexts) then you might want to increase this value, but for most use cases 64 should be fine.
